### ISSUE TITLE
NavLink Missed Migration

### ISSUE THREAD

**Issue by daddasoft** [mantinedev/mantine-v7#21]
### What package has an issue

@mantine/core

### Describe the bug

the navlink component isn't yet implemented. 

is it coming or will be deprecated ?

### What version of @mantine/hooks page do you have in package.json?

7

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by pankajparashar** [comment]
I hope NavLink is coming. I use it extensively in my project.

**Comment by FinnRG** [comment]
It was added in ab15c963436a2bd49fb0294875fd2e0c941cacba and will probably be included in the next version.

**Comment by daddasoft** [comment]
great to see that thanks
