### ISSUE TITLE
MultiSelect / Select with label+value data arrays render selected options incorrectly

### ISSUE THREAD

**Issue by robertjpayne** [mantinedev/mantine-v7#22]
### What package has an issue

@mantine/core

### Describe the bug

Both Select/MultiSelect accept data formats which can be:

```
data={[
  {value: "one", label: "One"},
  {value: "two", label: "Two"},
  {value: "three", label: "Three"}
]}
```

When using data like this the dropdown selector correctly renders the `label` value but the input field always renders the `value` of the selected options.

It should instead render the `label` value.

### What version of @mantine/hooks page do you have in package.json?

7.0.0-alpha.22

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by ioson** [comment]
Can confirm this bug. Happens with grouped options as well.

**Comment by boris-arkenaar** [comment]
I'm seeing the same with MultiSelect.

**Comment by boris-arkenaar** [comment]
To me it seems that this issue has not been solved in `7.0.0-beta.1`.

**Comment by rtivital** [comment]
Don't worry, it will be fixed in one of the next beta releases, it is in the backlog

**Comment by boris-arkenaar** [comment]
Okay! Expected it to be there in the next release. Then I won't worry :) Thanks.
