### ISSUE TITLE
ActionIcon component default wrong size icon

### ISSUE THREAD

**Issue by MA-MacDonald** [mantinedev/mantine-v7#39]
### What package has an issue

@mantine/core

### Describe the bug

When using the ActionIcon component I need to specify the size and stroke on the Icon to have it display the same as the documentation. 

![image](https://github.com/mantinedev/mantine-v7/assets/7886459/9dc2f104-0649-47dc-96ef-779b194fee35)
![image](https://github.com/mantinedev/mantine-v7/assets/7886459/838ccf17-d85e-4150-b91f-7e6eb54c5bfa)

![image](https://github.com/mantinedev/mantine-v7/assets/7886459/1d7afa37-8aa6-40c7-893a-de58cbcda18b)

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0-beta.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by teh23** [comment]
I think there is an old example on the website, locally i have:
![image](https://github.com/mantinedev/mantine-v7/assets/14942614/e205a1d7-c716-4173-b5c1-c6b9aa8257fc)
