### ISSUE TITLE
themeToVars don't export other object from createTheme

### ISSUE THREAD

**Issue by Uniiq** [mantinedev/mantine-v7#48]
### What package has an issue

@mantine/vanilla-extract

### Describe the bug

I have no access to the `other` object in vanilla-extract. Is this intentional or a bug? 

I resolved the issue with a direct theme import into my css file and load it directly from there. If this the correct way can someone told me how to create a interface for the other object?

Thanks for the help!

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0-beta.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
There is no way to resolve these variables. If you need to access these values, import theme object directly.

**Comment by Uniiq** [comment]
@rtivital thanks you for the quick answer. Any idea how to type the `other` object in v7? Because the v6 way is not working.
