### ISSUE TITLE
Indicator prop radius isn’t work properly

### ISSUE THREAD

**Issue by plastininikolay** [mantinedev/mantine-v7#54]
### What package has an issue

@mantine/core

### Describe the bug

In the Indicator component, the border-radius style differs in display at px or rem values at different sizes. For this reason, it is better to use constants with percentages for the border-radius style to unify the display

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0-beta.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
Can you provide an example code with an incorrect border-radius?

**Comment by plastininikolay** [comment]
https://codesandbox.io/p/sandbox/divine-snowflake-pzmhc6?file=/src/App.tsx:24,18

**Comment by rtivital** [comment]
It is not planned to be changed, radius in % is not the same as radius in other units. See example – https://codesandbox.io/s/sleepy-bardeen-vx5h49?file=/src/App.tsx
