### ISSUE TITLE
Navbar missing from v7

### ISSUE THREAD

**Issue by pankajparashar** [mantinedev/mantine-v7#63]
### What package has an issue

@mantine/core

### Describe the bug

Navbar and Aside as separate components available in v6 (https://mantine.dev/core/app-shell/#navbar-and-aside-components). v7 is missing these two components.

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0-beta.5

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment]
It is described in the changelog – https://v7.mantine.dev/changelog/7-0-0#appshell-changes
