### ISSUE TITLE
NativeSelect have ID attribute error

### ISSUE THREAD

**Issue by dejurin** [mantinedev/mantine-v7#9]
### What package has an issue

@mantine/core

### Describe the bug

Different IDs are generated on the client and server sides, and the ID is the same for all elements.

<img width="751" alt="Screenshot 2023-07-21 at 20 32 59" src="https://github.com/mantinedev/mantine-v7/assets/4470015/f53d9755-17a0-44b0-964e-82fab7049476">

<img width="984" alt="Screenshot 2023-07-21 at 20 29 10" src="https://github.com/mantinedev/mantine-v7/assets/4470015/93e4b197-8185-4c1c-9ae3-8c0c40930834">

**HTML output**:

```HTML
          <select class="mantine-SbVPkHB mantine-Input-input mantine-NativeSelect-input" 
data-variant="default" aria-invalid="false" aria-describedby="mantine-R3bddadkq-description" 
id="mantine-R3bddadkq-input">
            <option value="React">React</option>
            <option value="Angular">Angular</option>
            <option value="Vue">Vue</option>
          </select>
          
          <select class="mantine-SbVPkHB mantine-Input-input mantine-NativeSelect-input" 
data-variant="default" aria-invalid="false" aria-describedby="mantine-R5bddadkq-description"
id="mantine-R5bddadkq-input">
            <option value="React">React</option>
            <option value="Angular">Angular</option>
            <option value="Vue">Vue</option>
          </select>
          
          <select class="mantine-SbVPkHB mantine-Input-input mantine-NativeSelect-input" 
data-variant="default" aria-invalid="false" aria-describedby="mantine-R7bddadkq-description" 
id="mantine-R7bddadkq-input">
            <option value="React">React</option>
            <option value="Angular">Angular</option>
            <option value="Vue">Vue</option>
          </select>
```

```JSON
"@mantine/core": "7.0.0-alpha.17",
"@mantine/hooks": "7.0.0-alpha.17",
"@next/bundle-analyzer": "^13.4.11",
"clsx": "^2.0.0",
"lodash": "^4.17.21",
"next": "13.4.11",
"next-intl": "^2.19.0",
"react": "18.2.0",
"react-dom": "18.2.0",
```

### What version of @mantine/hooks page do you have in package.json?

7.0.0-alpha.17

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/github/dejurin/mantine7-nextjs/main

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by dejurin** [comment]
Update

<img width="681" alt="Screenshot 2023-07-23 at 19 09 03" src="https://github.com/mantinedev/mantine-v7/assets/4470015/19d1f8b0-fec2-41ab-9d0d-0c341dee9e63">

https://g3693t-3000.csb.app/grid

**Comment by minleychris** [comment]
I can see this on the DatePickerInput too.

**Comment by teh23** [comment]
> I can see this on the DatePickerInput and dropdown menus too.

it was nextjs thing https://github.com/shadcn-ui/ui/issues/1023 tested on 13.4.18 works well

**Comment by minleychris** [comment]
Thanks, that sorted it for me!

**Comment by dejurin** [comment]
This problem is solved.
